### ISSUE TITLE
[BUG]: qdt.exe - qprofiles-manager sync_mode doesn't work with argument only_different_version 

### ISSUE THREAD

**Issue by EmilieEPLoire** [Guts/qgis-deployment-cli#223]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0.20.0

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

sync_mode works with argument _overwrite_ but  doesn't work with argument _only_different_version_ 
![v20-erreur_synchronisation](https://user-images.githubusercontent.com/52237106/223956730-2b0f8409-9e77-40eb-b8bd-95cc8da0dd4f.PNG)

**Comment by Guts** [comment]
Thanks @EmilieEPLoire ,

Can you provide the scenario file please?
