### ISSUE TITLE
[BUG]: Use QGIS LTR 3.28.4 path as default 

### ISSUE THREAD

**Issue by EmilieEPLoire** [Guts/qgis-deployment-cli#244]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0.22.3

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Related resources

[scenario_QgisConf.qdt.yml.txt](https://github.com/Guts/qgis-deployment-cli/files/10958129/scenario_QgisConf.qdt.yml.txt)

### Description of the bug

Shortcut on desktop is to qgis 3.28 however Qgis 3.22 is installed.

### Relevant log output

```Shell
PS Z:\installqgis> .\QGISDeploymentToolbelt_Latest.exe -s scenario_QgisConf.qdt.yml                                     2023-03-13 14:50:33||WARNING||shortcuts||115||Executable does not exist: C:\Program Files\QGIS 3.28.4\bin\qgis-ltr-bin.exe. Shortcuts might not work. Check and fix your scenario.
```

**Comment by EmilieEPLoire** [comment]
Resolve with $env:QDT_QGIS_EXE_PATH="C:\\path\\to\\qgis-ltr-bin.exe"

**Comment by Guts** [comment]
> Shortcut on desktop is to qgis 3.28 however Qgis 3.22 is installed.

The default path changed in the latest version (see changelog: https://guts.github.io/qgis-deployment-cli/development/history.html#id1)

You can set it as environment variable `QDT_QGIS_EXE_PATH` or in your scenario `settings` section.
