### ISSUE TITLE
[BUG]: Profile deployment is not achieved properly when the profile name includes a space character

### ISSUE THREAD

**Issue by imallet** [Guts/qgis-deployment-cli#292]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0.24.0

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Related resources

- Extract of the profile.json file :
Profile name is **"Cadastre GL"**
![Capture1](https://github.com/Guts/qgis-deployment-cli/assets/7337488/f0638b2c-1661-40fb-beae-622057b78e86)

[profile.zip](https://github.com/Guts/qgis-deployment-cli/files/12018013/profile.zip)

- Extract of the scenario file :
First I synchronize my profile from Git with qprofiles-manager
Then I create a shortcut for the profile named "Cadastre GL" :
![Capture2](https://github.com/Guts/qgis-deployment-cli/assets/7337488/e01d7f35-8dc9-4078-8144-051250af4ecb)

[scenario-cadastre.qdt.zip](https://github.com/Guts/qgis-deployment-cli/files/12018008/scenario-cadastre.qdt.zip)

### Description of the bug

When the profile name includes a space character, only the 1st part of the name (before the space character) is used to name the profile (eg : "Cadastre" instead of "Cadastre GL") :
![Capture3](https://github.com/Guts/qgis-deployment-cli/assets/7337488/1e213a03-3974-41cb-be78-e33ce4d9cdbf)

The shortcut for the profile is not created because the name of the profile defined in the shortcuts-manager in the scenario file doesn't match the name of an existing profile (see logfile, **line 93**)

[QGISDeploymentToolbelt_0.24.0.log](https://github.com/Guts/qgis-deployment-cli/files/12017969/QGISDeploymentToolbelt_0.24.0.log)

### Relevant log output

```Shell
2023-07-11 20:18:38||DEBUG||generic_job||57||3 profiles found within C:\Users\sitimal\.cache\qgis-deployment-toolbelt\grandlyon
2023-07-11 20:18:38||INFO||job_profiles_synchronizer||167||3 downloaded profiles: Cadastre, GrandLyon, GrandLyon-2


2023-07-11 20:18:41||DEBUG||generic_job||57||3 profiles found within C:\Users\sitimal\.cache\qgis-deployment-toolbelt\grandlyon
2023-07-11 20:18:41||ERROR||job_shortcuts||182||Unable to get a matching profile among downloaded ones with the name: Cadastre GL
```

**Comment by Guts** [comment]
Thanks for taking time to report.

The issue was occurring in Shortcut Manager job.

Fix shipped in version 0.29.0: https://github.com/Guts/qgis-deployment-cli/releases/tag/0.29.0
