### ISSUE TITLE
[BUG]: QDT0.28 does not recognise a Git repository as a Git repository

### ISSUE THREAD

**Issue by NROLLANDGrandlyon** [Guts/qgis-deployment-cli#344]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

Windows_QGISDeploymentToolbelt_0-28-0.exe

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

In the scenario repository is defined as 
protocol: git
source: file://\\svcficapp01-dev.grandlyon.fr\APPLISIT\APPLI\LSM\QGIS\DEV\qgis3

This directory is a Git repo synchronised with Git Desktop.
It works fine with version 0.26 but not with version 0.28 with the error message:

Traceback (most recent call last):
  File "qgis_deployment_toolbelt\commands\deployment.py", line 201, in run
  File "qgis_deployment_toolbelt\jobs\job_profiles_synchronizer.py", line 121, in run
  File "qgis_deployment_toolbelt\profiles\local_git_handler.py", line 68, in __init__
dulwich.errors.NotGitRepository: \\svcficapp01-dev.grandlyon.fr\APPLISIT\APPLI\LSM\QGIS\DEV\qgis3 is not a valid Git repository.

Same error with another repo

### Steps to reproduce

run Windows QDT 0.28.exe with a Git repo in qprofiles-manager

**Comment by Guts** [comment]
Thanks for taking time to report here. Indeed, the local git repositories were not recognized anymore.

Fix shipped in version 0.29.0: https://github.com/Guts/qgis-deployment-cli/releases/tag/0.29.0
