### ISSUE TITLE
[BUG]: quand il est créé par QDT et vide, le répertoire .cache\qgis-deployment-toolbelt n'est pas recunnu comme dépot Git

### ISSUE THREAD

**Issue by NROLLANDGrandlyon** [Guts/qgis-deployment-cli#354]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

Windows_QGISDeploymentToolbelt_0-29-0.exe

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

Sur un PC sur lequel QDT n'a jamais tourné, quand on le lance il s'arrête à la première étape avec les messages d'erreur:

||ERROR||git_handler_base||177||C:\Users\sitnrol\.cache\qgis-deployment-toolbelt is not a valid Git repository. Trace: No git repository was found at C:\Users\sitnrol\.cache\qgis-deployment-toolbelt
||ERROR||git_handler_base||177||C:\Users\sitnrol\.cache\qgis-deployment-toolbelt is not a valid Git repository. Trace: No git repository was found at C:\Users\sitnrol\.cache\qgis-deployment-toolbelt
||CRITICAL||git_handler_base||457||Case not handle. Context: C:\Users\sitnrol\.cache\qgis-deployment-toolbelt (empty=False) valid repo=False

Log ci-joint écrit dans le répertoire C:\Users\sitnrol\.cache\qgis-deployment-toolbelt\logs
[QGISDeploymentToolbelt_0.29.0.log](https://github.com/Guts/qgis-deployment-cli/files/13648427/QGISDeploymentToolbelt_0.29.0.log)

### Steps to reproduce

Sur un PC sur lequel QDT n'a jamais tourné.
Le répertoire .cache n'existe pas
Lancer QDT en pointant sur un scénario valide

### Relevant log output

```Shell
2023-12-12 13:01:30||ERROR||git_handler_base||177||C:\Users\sitnrol\.cache\qgis-deployment-toolbelt is not a valid Git repository. Trace: No git repository was found at C:\Users\sitnrol\.cache\qgis-deployment-toolbelt
2023-12-12 13:01:30||ERROR||git_handler_base||177||C:\Users\sitnrol\.cache\qgis-deployment-toolbelt is not a valid Git repository. Trace: No git repository was found at C:\Users\sitnrol\.cache\qgis-deployment-toolbelt
2023-12-12 13:01:30||CRITICAL||git_handler_base||457||Case not handle. Context: C:\Users\sitnrol\.cache\qgis-deployment-toolbelt (empty=False) valid repo=False
```

**Comment by Guts** [comment]
Hello @NROLLANDGrandlyon,

Merci de prendre le temps de signaler ici l'anomalie.

Le fichier de log est très petit. As-tu bien lancé QDT en mode verbeux (comme indiqué dans le formulaire de signalement) soit avec l'option `-vvv`, soit avec la variable d'environnement soit avec le réglage dans le scénario ?

Peux-tu donner davantage de détails sur le contexte stp ? Notamment :

- Comment est défini le scénario (variable d'environnement, fichier à côté de l'exe, chemin passé en paramètre de l'exécutable) ?
- quelle est la configuration du job profiles-manager dans le scénario ?

Car je n'arrive pas à reproduire le problème (en supprimant le dossier `~/.cache/qgis-deployment-toolbelt`) et pour information QDT est automatiquement exécuté à chaque modification de code dans un environnement multi-plateforme et "neuf" càd sans exécution précédente.

**Comment by NROLLANDGrandlyon** [comment]
OK je vois ça m'était déjà arrivé et comme je suis retombé dessus je l'ai signalé mais ça doit être le chemin vers le scénario qui n'est pas reconnu. Je vais voir.

**Comment by NROLLANDGrandlyon** [comment]
J'ai reproduit en mode verbose, voici le log. QDT a bien accès au scénario.
Je ne reproduit pas non plus sur ma machine quand je supprime le répertoire .cache
[QGISDeploymentToolbelt_0.29.0.log](https://github.com/Guts/qgis-deployment-cli/files/13657961/QGISDeploymentToolbelt_0.29.0.log)

Je lance QDT par un .bat qui contient la cmd:
.\QGISDT_0-29-0.exe --verbose --scenario \\svcficapp01-dev.grandlyon.fr\APPLISIT\APPLI\LSM\QGIS\DEV\qgis3\scenario\scenario_deploiement_QGIS_GL_v0.5.qdt.yml
avec le fichier QGISDT_0-29-0.exe à coté dans le même répertoire

Ci joint le scénario renommé en .txt car le .yml ne passe pas ici.
[scenario_deploiement_QGIS_GL_v0.5.qdt.txt](https://github.com/Guts/qgis-deployment-cli/files/13658004/scenario_deploiement_QGIS_GL_v0.5.qdt.txt)

QDT crée bien le répertoire .cache/qgis-deployment-toolbelt/log

Avec Teams, il y a moyen de prendre la main sur le poste à coté de moi si besoin. (sauf le mercredi).

**Comment by NROLLANDGrandlyon** [comment]
J'ai testé sur un autre PC et c'est pareil.
Je l'ai lancé directement par la cmd 
QGISDT_0-29-0.exe --verbose --scenario scenario_deploiement_QGIS_GL_v0.5.qdt.yml avec les fichiers dans le même répertoire et le résultat est exactement le même.

**Comment by Guts** [comment]
Peux-tu retester avec la version 0.30.0 stp ? https://github.com/Guts/qgis-deployment-cli/releases/tag/0.30.0

> Avec Teams, il y a moyen de prendre la main sur le poste à coté de moi si besoin. (sauf le mercredi).

Tu m'envoies un lien par mail pour demain ?

**Comment by NROLLANDGrandlyon** [comment]
Alors en fait c'est TeamViewer. Je préfère ne pas communiquer la dessus ici. Uniquement par email ou téléphone.

**Comment by NROLLANDGrandlyon** [comment]
J'ai testé avec la version 0.30 et ça fonctionne parfaitement cette fois. Les profils et icônes sont copiés correctement.

**Comment by Guts** [comment]
Cool !

Je ferme donc ce ticket et on voit pour les autres soucis demain ensemble avec un café teams :)
